### ISSUE TITLE
UI Config never saves

### ISSUE THREAD

**Issue by randomhouston** [grzegorz914/homebridge-denon-tv#190] opened 2023-04-12 15:48 UTC
When I try to add my receiver and setting via the UI the config never saves into hombridge.

**Comment by john2691** [comment] 2023-04-12 19:37
Same issue, rolling back to an older version (4.1.0) doesn't solve it either.

**Comment by partymild** [comment] 2023-04-15 18:20
Same issue here, fresh install and it never saves the config. I manually installed the latest 3.x version for it to work; the different 4.x versions all had the same problem.

**Comment by john2691** [comment] 2023-04-16 21:02
> Same issue here, fresh install and it never saves the config. I manually installed the latest 3.x version for it to work; the different 4.x versions all had the same problem.

This workaround fixed it for me also.

**Comment by randomhouston** [comment] 2023-04-18 17:35
same, I did the rollback to version 3 workaround and have my receiver back in homekit too

**Comment by julians** [comment] 2023-04-28 20:10
Same for me

**Comment by TechnoDarkOne** [comment] 2023-05-12 00:54
I have the same issue, it won't save the config.

**Comment by grzegorz914** [comment] 2023-05-24 07:01
I don't see any issue with config save, all working correct. Check please your environment, permission, etc...

**Comment by cosnomode** [comment] 2023-06-04 15:57
same here, other config for other plugins works fine.

**Comment by vanakema** [comment] 2023-06-05 22:18
same here, no issues with my other plugins

**Comment by Coder84619** [comment] 2023-06-12 01:22
Same issue for me. Tried to change the IP and it won't save.

**Comment by grzegorz914** [comment] 2023-06-12 03:16
What happening if you change the config.json manually?

**Comment by Coder84619** [comment] 2023-06-13 03:04
> What happening if you change the config.json manually?

Where is it located?

**Comment by grzegorz914** [comment] 2023-06-30 05:57
Check please #196

**Comment by alegend2k** [comment] 2023-06-30 06:08
Great maybe this is the issue for others also! Try another browser or maybe homemanager app on IOS...there it also works...

**Comment by partymild** [comment] 2023-06-30 08:35
I've tried with Chrome, Firefox and Edge (newest versions) - same issue, changes I make for the plugin via config-ui doesn't save.

**Comment by alegend2k** [comment] 2023-06-30 09:30
tried it with an app like homemanger? this was the first step i did and there it saved! then i went to safari und here it saved also...

**Comment by tjq100** [comment] 2023-07-05 11:37
Homemanager app worked for me as well.  They offer a free 14 day trial but seems like a nice app so I may just get it.

**Comment by grzegorz914** [comment] 2023-07-05 11:39
@tjq100 

can you try with safari browser?

**Comment by tjq100** [comment] 2023-07-05 13:58
I was using Safari on an iPad when it wasn’t working.  Just checked and still not saving changes via Safari on iPad.  Here’s a video in case it helps.  Happy to troubleshoot other things if you’d like.  Just let me know.  Cheers,Tim1 Videoshare.icloud.comSent from my iPadOn Jul 5, 2023, at 7:40 AM, Grzegorz ***@***.***> wrote:﻿
@tjq100
can you try with safari browser?

**Comment by grzegorz914** [comment] 2023-07-05 14:25
What other things would You Troubleshoot ?

**Comment by alegend2k** [comment] 2023-07-05 14:27
> Homemanager app worked for me as well. They offer a free 14 day trial but seems like a nice app so I may just get it.

let me know if it works with that - for me it did...and since I used it it works on my mac also again...

**Comment by tjq100** [comment] 2023-07-05 16:02
Should have said, if you want me to try anything elseSent from my iPadOn Jul 5, 2023, at 10:28 AM, alegend2k ***@***.***> wrote:﻿

Homemanager app worked for me as well. They offer a free 14 day trial but seems like a nice app so I may just get it.

let me know if it works with that - for me it did...and since I used it it works on my mac also again...

**Comment by shadegits** [comment] 2023-07-19 03:58
Same issue, could not delete existing buttons using safari on an iPhone.  Worked just fine using safari on a Mac though.

**Comment by ValadAmoleo** [comment] 2023-07-21 06:59
Same issue here.  Having to use the last v3 for it to work.  Moving to v4 also stops my second device from working.

**Comment by grzegorz914** [comment] 2023-07-21 07:03
Please update Config-Ui-X to 4.50.5-test.6 and let me know

**Comment by grzegorz914** [comment] 2023-07-21 07:05
@ValadAmoleo 

please open new issue regarding stop working of second device, post the config and debug log

**Comment by grzegorz914** [comment] 2023-08-06 06:34
Any info after update to: 
Config-Ui-X to 4.50.5-test.

**Comment by partymild** [comment] 2023-08-08 09:47
No change for me unfortunately, tried it with `homebridge-config-ui-x v4.50.5-test.6` and `homebridge-denon-tv v4.3.1` on `homebridge v1.6.1.` with `Node.js Version	v18.13.0`

**Comment by nickp85** [comment] 2023-09-10 01:14
I was able to edit with Safari, not Chrome, very strange

**Comment by hubertm600** [comment] 2023-10-22 11:37
I can save setting with android phone chrome broswer

**Comment by Travel-tech** [comment] 2023-12-07 19:38
Issue still present with latest update. Still need to save the config using Safari. Chrome/Chromium/Edge based browsers simply don't work.

**Comment by Jelledb** [comment] 2023-12-26 12:10
Same issue here. Config never saves from the UI

**Comment by bsoener** [comment] 2024-01-14 08:29
Had exactly the same problem always had to edit manually. This does not work with Firefox. I then used Safari and it works with Safari.

**Comment by grzegorz914** [comment] 2024-01-15 17:14
Probably fixed, 4.7.0-beta published to test, please let me know.

**Comment by bsoener** [comment] 2024-01-16 18:20
I have the latest version: 4.7.1 and I still can't change anything with Firefox

**Comment by grzegorz914** [comment] 2024-01-16 19:16
It’s not fixed yet

**Closed** 2024-01-17 09:17 UTC

**Comment by grzegorz914** [comment] 2024-01-17 09:21
Fixedin 4.8.0

**Comment by anon1y4012** [comment] 2024-01-17 15:01
Confirmed its working now, nice work @grzegorz914
